/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "accessible-palette-generator",
  "name": "Palette Lab",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "A calm palette for a meditation app",
      "does": "Generates the palette and runs the contrast audit."
    },
    {
      "say": "Make the accent warmer but keep it accessible",
      "does": "Adjusts the accent and re-checks contrast."
    },
    {
      "say": "Export it as Tailwind",
      "does": "Shows the Tailwind config ready to copy."
    }
  ]
};
